### ISSUE TITLE
fix: add SqsManagedSseEnabled to SQS resources explicitly

### ISSUE THREAD

**Issue by sliedig** [aws-samples/aws-serverless-developer-experience-workshop-python#16]
Internal code scanning requirement. Example:

```
PropertiesEventBusRuleDLQ:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      SqsManagedSseEnabled: true
      MessageRetentionPeriod: 1209600 # Maximum value, 1,209,600 (14days)
      Tags:
        - Key: project
          Value: AWS Serverless Developer Experience
        - Key: service
          Value: !Sub "{{resolve:ssm:/UniProp/${Stage}/UnicornPropertiesNamespace}}"
        - Key: stage
          Value: !Ref Stage
```
